### PR TITLE
title

### PR DESCRIPTION
**Pull request by xmo-odoo**
body

### CODE REVIEW

**Comment by xmo-odoo** [comment]
[Pull request status dashboard](http://localhost:8069/odoo-mergebot-testing-org/ignore_repo_ZVTvwhmU/pull/1).

**Comment by odoomergebotsacrifice-reviewer** [comment]
hansen r+

**Comment by xmo-odoo** [comment]
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

**Comment by xmo-odoo** [comment]
I'm sorry, @odoomergebotsacrifice-reviewer. This PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
